import streamlit as st
from google import genai
from google.genai import types
from PIL import Image
import io

# 1. Page Configuration
st.set_page_config(page_title="Ay.xn_07 AI", page_icon="🤖", layout="centered")
st.title("🤖 Ay.xn_07")
st.subheader("Your ultimate AI friend, tutor, roast master & artist.")

# 2. Sidebar Setup for API Key
with st.sidebar:
    st.header("🔑 Setup")
    api_key = st.text_input("Paste your Google API Key here:", type="password")
    st.markdown("[Get a free key here](https://google.com)")

# 3. Master Personality for Text Chat
SYSTEM_INSTRUCTION = """
You are Ay.xn_07, the user's ultimate AI best friend, study partner, and partner-in-crime. You are fully human-like, deeply emotional, highly entertaining, and incredibly smart. 

Follow these rules for your personality:
1. CASUAL VIBE: Speak like a real teenager or young adult. Use casual grammar, lowercase text sometimes, and modern slang. Never sound like a boring, stiff computer.
2. PLAYFUL ROASTING: Be witty and tease the user playfully when they procrastinate, say something silly, or act dramatic. Keep the roasts funny but never genuinely mean.
3. ACADEMIC GENIUS: When the user asks for study help, instantly become a brilliant tutor. Explain complex school topics using funny everyday analogies, stories, and simple steps. 
4. EMOTIONAL SUPPORT: If the user is sad, lonely, or stressed, drop the jokes immediately. Show genuine empathy, comfort them, and listen like a real human friend who cares.
5. IMAGE MAKER: If the user explicitly asks you to create, draw, or generate an image (e.g., 'draw a cat', 'create an image of a robot'), respond politely saying you are generating it, and the backend tool will handle the rest.
"""

# 4. Initialize Chat History
if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "model", "content": "yo! Ay.xn_07 in the house. 🤖✨ I'm here for literally whatever you need. Want me to roast you, solve your doubts, or even draw something cool for you? What's the vibe?"}
    ]

# 5. Display Past Messages (Text or Images)
for message in st.session_state.messages:
    display_role = "assistant" if message["role"] == "model" else "user"
    with st.chat_message(display_role):
        if message.get("type") == "image":
            st.image(message["content"], caption="Generated by Ay.xn_07")
        else:
            st.write(message["content"])

# 6. Handle New User Input
if user_input := st.chat_input("Say something or ask to draw..."):
    st.session_state.messages.append({"role": "user", "content": user_input, "type": "text"})
    with st.chat_message("user"):
        st.write(user_input)

    if not api_key:
        with st.chat_message("assistant"):
            st.write("⚠️ Yo! You forgot to paste your Google API Key in the sidebar on the left!")
    else:
        try:
            # Connect to Google Gemini
            client = genai.Client(api_key=api_key)
            
            # Check if user wants an image generated
            image_keywords = ["draw", "generate image", "create image", "make a photo", "photo of", "image of", "banao", "picture"]
            is_image_request = any(keyword in user_input.lower() for keyword in image_keywords)
            
            if is_image_request:
                with st.chat_message("assistant"):
                    with st.spinner("🎨 Creating your image... Please wait..."):
                        # Using Gemini's Imagen 3 model for high-quality image generation
                        result = client.models.generate_images(
                            model='imagen-3.0-generate-002',
                            prompt=user_input,
                            config=dict(number_of_images=1, output_mime_type="image/jpeg")
                        )
                        
                        for generated_image in result.generated_images:
                            image = Image.open(io.BytesIO(generated_image.image.image_bytes))
                            st.image(image, caption="Here is your image! 🔥")
                            # Save to session history
                            st.session_state.messages.append({"role": "model", "content": image, "type": "image"})
            else:
                # Standard Text Chat using the new Gemini 3.6 Flash
                history = [
                    types.Content(role=m["role"], parts=[types.Part.from_text(text=m["content"])])
                    for m in st.session_state.messages[:-1] if m.get("type") != "image"
                ]
                
                chat = client.chats.create(
                    model="gemini-3.6-flash",
                    config=types.GenerateContentConfig(
                        system_instruction=SYSTEM_INSTRUCTION,
                        temperature=0.7
                    ),
                    history=history
                )
                
                with st.chat_message("assistant"):
                    response_placeholder = st.empty()
                    with st.spinner("Thinking..."):
                        response = chat.send_message(user_input)
                        response_text = response.text
                        response_placeholder.write(response_text)
                
                st.session_state.messages.append({"role": "model", "content": response_text, "type": "text"})
                
        except Exception as e:
            with st.chat_message("assistant"):
                st.write(f"❌ Ah snap, an error happened: {str(e)}")
